# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: virtual_actor.proto for package 'virtual_actor'

require 'grpc'
require_relative 'virtual_actor_pb'

module VirtualActor
  module ActorService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'virtual_actor.ActorService'

      rpc :SendMessage, ::VirtualActor::MessageRequest, ::VirtualActor::MessageResponse
      rpc :GetActorState, ::VirtualActor::ActorStateRequest, ::VirtualActor::ActorStateResponse
    end

    Stub = Service.rpc_stub_class
  end
end
