# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virtual_actor.proto

require 'google/protobuf'


descriptor_data = "\n\x13virtual_actor.proto\x12\rvirtual_actor\"d\n\x0eMessageRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\x12\x12\n\nactor_type\x18\x02 \x01(\t\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\x12\x17\n\x0fserialized_args\x18\x04 \x01(\x0c\"I\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x0c\"%\n\x11\x41\x63torStateRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\"D\n\x12\x41\x63torStateResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\x0c\x32\xb6\x01\n\x0c\x41\x63torService\x12N\n\x0bSendMessage\x12\x1d.virtual_actor.MessageRequest\x1a\x1e.virtual_actor.MessageResponse\"\x00\x12V\n\rGetActorState\x12 .virtual_actor.ActorStateRequest\x1a!.virtual_actor.ActorStateResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module VirtualActor
  MessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtual_actor.MessageRequest").msgclass
  MessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtual_actor.MessageResponse").msgclass
  ActorStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtual_actor.ActorStateRequest").msgclass
  ActorStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("virtual_actor.ActorStateResponse").msgclass
end
